### ISSUE TITLE
Pancreas_atac h5ad object can't be downloaded

### ISSUE THREAD

**Issue by xfchen0912** [theislab/mubind#130]
Hi,
The file in the Dropbox URL (https://www.dropbox.com/scl/fi/scs2qchvzuzvwndxphpgn/pancreas_multiome_2022_processed_atac.h5ad?rlkey=sd7fdtj898as0a46tsoyr476i&dl=0) shows that it has been deleted.
Could you please re-upload or update the correct download url?

**Comment by ilibarra** [comment]
Hi @xfchen0912 ,

Thanks for noticing this missing URL! I have updated it to a new one in the development and main branches.
https://github.com/theislab/mubind/blob/main/mubind/datasets/datasets.py#L546

Please close is no other comments, or refer to other h5ad reading issues. Cheers,

**Comment by shunyasanuma** [comment]
Hello @xfchen0912,

Can you load the Pancreas_atac h5ad dataset from Dropbox? 
I downloaded the file, but it doesn’t seem to be in the correct h5ad format.
Thank you.

**Comment by shunyasanuma** [comment]
Can you also download `motif_annotations.xlsx` without any problems?

**Comment by shunyasanuma** [comment]
@xfchen0912
Can you also download/load `motif_annotations.xlsx` without any problems?

**Comment by xfchen0912** [comment]
Hi @shunyasanuma，
Sry for the late response. I am able to read it successfully.
![image](https://github.com/user-attachments/assets/c4b25651-31d1-4f01-8291-9c7c31ab8241)
And I can download the motif_annotations.xlsx
![image](https://github.com/user-attachments/assets/ffa3de3f-2bbf-48bf-902e-71d92d1df15c)

**Comment by shunyasanuma** [comment]
Thank you for your reply! 
I was eventually able to load the files.
