### ISSUE TITLE
Improve documentation of pancreas multiome dataset

### ISSUE THREAD

**Issue by MUCDK** [theislab/mubind#133]
Please document the datasets better, especially the pancreas multiome, as it's not officially published yet (will be end of the year together with the moscot paper). So please explicitly refer to the moscot preprint in the docs. The raw data is now available at https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE275562

**Comment by ilibarra** [comment]
@MUCDK Thanks for the suggestion! The ref. for each dataset is now at the beginning of each training notebook using the {cite} syntax e.g.
https://mubind.readthedocs.io/en/latest/notebooks/single_cell/02_2_1_scatac_multiome_pancreas_priors_train.html
https://mubind.readthedocs.io/en/latest/references.html
Thank you for the GEO link. We also included it in the panc. endocrinogenesis tutorial as well.
Indicate if you mean additional documentation for the datasets and/or examples from other repos. We'll keep improving docs based on that.

**Comment by ilibarra** [comment]
This seems covered for now. Please indicate if additional documentation troubleshooting is needed by reopening the issue. Thank you!
