### ISSUE TITLE
Generating atac.h5ad

### ISSUE THREAD

**Issue by shunyasanuma** [theislab/mubind#136]
Hello, 

Can you add a tutorial on how to generate `pancreas_multiome_2022_processed_atac.h5ad` to the existing tutorial 'Mouse Pancreatic Endocrinogenesis (scATAC-seq) | Training with an RNA-Dynamics kNN-Graph'?

**Comment by ilibarra** [comment]
The general workflow requires (i) an scATAC-seq file in AnnData format, processed from CellRanger or another, and (ii) a graph representation for dynamics, which is generated from the ` velocity_graph` using scVelo. Instructions for the latter are here.
https://scvelo.readthedocs.io/en/stable/getting_started.html

I need more instructions for this request. How early would you imagine a tutorial should be, or (i)/(ii) and both? I marked this as documentation. In case of another crucial step unclear, let us know.

Thank you!

**Comment by shunyasanuma** [comment]
My highest priority is (i) scATAC-seq file in AnnData format. 
It would be great if you could release it soon. 
How long do you expect to need?

**Comment by ilibarra** [comment]
I see. For (i), we cannot re-document here as priority, and this is covered in other scverse packages. Please check the sc-best practices book, and/or AnnData/scanpy/muon tutorials for this. Attaching one link as first referral. Potentially, open an issue in those if the provided docs are not covering your files format. For muBind-related issues after preparing such AnnData objects, let us know via new issues. Thank you.
https://www.sc-best-practices.org/chromatin_accessibility/quality_control.html
